[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "transcriber"
version = "0.1.0"
dependencies = [
  "spacy>=3.8",
  "llama-cpp-python>=0.3",
  "fpdf2>=2.8",
  "watchdog>=6.0",
  "google-api-python-client>=2.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
transcriber = "transcriber.main:main"